### ISSUE TITLE
Issue Title: Rename "Delete note" to "Delete to-do" in To-Do Context Menu

### ISSUE THREAD

**Issue by abhishekshah5486** [priyasirohi09/joplin#115]
### Operating system

macOS

### Joplin version

Joplin 3.0.8 (dev, darwin)

### Desktop version info

macOS Sonoma Version 14.5

### Current behaviour

When creating or managing to-dos, the context menu displays the option "Delete note" instead of a more appropriate label such as "Delete to-do." This causes confusion for users as the option does not clearly reflect the action they intend to perform.

**Steps to Reproduce:**

- Open the application.
- Navigate to a notebook and click on "New to-do."
- Click on the context menu in the to-do editor.

**Screenshot**

<img width="710" alt="Screenshot 2024-07-01 at 2 48 43 PM" src="https://github.com/priyasirohi09/joplin/assets/141479542/fdca6ab6-b7e6-4e4e-91c3-62e7b63bf1c0">

<img width="1009" alt="Screenshot 2024-07-01 at 2 48 57 PM" src="https://github.com/priyasirohi09/joplin/assets/141479542/d698217e-99d9-42d5-ba1a-a4afa0531c31">

**Suggested Solution:**
Rename the "Delete note" option to "Delete to-do" when the user is in the to-do context. Ensure that context-sensitive options are provided based on whether the user is working with notes or to-dos.

### Expected behaviour

The context menu should display the option "Delete to-do" when managing to-do items to provide clear and relevant options based on the user's current context.

**Comment by abhinav26966** [comment]
I'd like to work on renaming "Delete note" to "Delete to-do" in the to-do context menu. Please assign this issue to me.

**Comment by DevMhrn** [comment]
@priyasirohi09 This seems to be a good issue , I would like to work on it and resolve it.

**Comment by harsh-791** [comment]
This seems to be a good issue , I would like to work on it and resolve it

**Comment by siddharthbaleja7** [comment]
I would like to work on it and resolve it

**Comment by NareshBiradar1** [comment]
I would like to work on this issue @priyasirohi09

**Comment by ruthwikchikoti** [comment]
I would like to work on this issue  @priyasirohi09

**Comment by Atharv-2004** [comment]
I would die to work on  this issue @priyasirohi09

**Comment by Yash020405** [comment]
I would like to resolve this issue @priyasirohi09

**Comment by Naresh-kumar-Thodupunoori** [comment]
I want to resolve this issue @priyasirohi09. As it is a good first issue, this will be a perfect issue to start contributing to open source.

**Comment by ankur-kalita** [comment]
i want to work on it @priyasirohi09

**Comment by Atharv-2004** [comment]
I would like to work on this @priyasirohi09

**Comment by its-harshitgoel** [comment]
I would like to work on it. Please assign it to me! @priyasirohi09

**Comment by Arnavya** [comment]
I would like to work on this issue

**Comment by abhishekshah5486** [comment]
@Atharv-2004 avoid dying :)
Let's see who gets the issue.
