### ISSUE TITLE
Add a "Dark Mode" Feature

### ISSUE THREAD

**Issue by Indrajeety993648** [priyasirohi09/joplin#122]
The note-taking application currently lacks a "Dark Mode" toggling option , which would be beneficial for users who prefer a darker interface, especially in low-light environments.

**Comment by srivastavaarpit977** [comment]
@priyasirohi09  I think this will enhance user experience...would like to work on this feature.

**Comment by OmMishra16** [comment]
Can this issue be assigned to me? I really want to contribute on this.
