### ISSUE TITLE
Right Click tools of both note and to-do shows Delete Note

### ISSUE THREAD

**Issue by ankur-kalita** [priyasirohi09/joplin#191]
### Operating system

Linux

### Joplin version

1.0.5

### Current behaviour

1. Both Note DropDown and Todo dropDown shows Delete Note
![notebug](https://github.com/priyasirohi09/joplin/assets/143007590/ea25d6c2-338d-4cf1-8050-ae5aa25428ce)
![todobug](https://github.com/priyasirohi09/joplin/assets/143007590/87177502-e9a0-4e37-8e89-24f1b5248a6e)

### Expected behaviour

1. The drop-down of to-do options should show Delete to-do

**Comment by Om-Midya** [comment]
I am dedicated developer and I believe this issue will help me test my capabilities. I whole heartily believe that I should be assigned this issue so that I can contribute to this wonderful project and its development.

**Comment by BHAV0207** [comment]
I would like to work on this issue

**Comment by ankur-kalita** [comment]
completed...thank you
