### ISSUE TITLE
Delete FIle permanently isn't working

### ISSUE THREAD

**Issue by CodeMaverick2** [priyasirohi09/joplin#69]
👉 Please follow one of these issue templates:
- https://github.com/laurent22/joplin/issues/new/choose

⚠️
The GitHub issue tracker is for **bugs** and **security issues** ONLY. For feature requests and support, please use the forum:
https://discourse.joplinapp.org/
⚠️

Note: to keep the backlog clean and actionable, issues may be immediately closed if they do not follow one of the above issue templates.

**Comment by arjun-kshirsagar** [comment]
@priyasirohi09 I would love to work on this issue.
Please assign it to me.
